start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 40
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 20
    inner.vertical =   20
    outer.left =       20
    outer.bottom =     20
    outer.top =        20
    outer.right =      20

[mode.main.binding]
    cmd-h = []     # Disable "hide application"
    cmd-alt-h = [] # Disable "hide others"

    alt-shift-c = 'reload-config'
    # cmd-alt-ctrl-shift-c = 'reload-config'

    alt-shift-space = 'layout floating tiling'
    # cmd-alt-ctrl-shift-space = 'layout floating tiling'

    alt-shift-f = 'fullscreen'
    # cmd-alt-ctrl-shift-f = 'fullscreen'

    alt-tab = 'workspace next'
    # cmd-alt-ctrl-tab = 'workspace next'
    alt-shift-tab = 'workspace prev'
    # cmd-alt-ctrl-shift-tab = 'workspace prev'

    alt-slash = 'layout tiles horizontal vertical'
    # cmd-alt-ctrl-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'
    # cmd-alt-ctrl-comma = 'layout accordion horizontal vertical'

    alt-shift-minus = 'resize smart -50'
    # cmd-alt-ctrl-shift-minus = 'resize smart -50'
    alt-shift-equal = 'resize smart +50'
    # cmd-alt-ctrl-shift-equal = 'resize smart +50'

    alt-h = 'focus left'
    # cmd-alt-ctrl-h = 'focus left'
    alt-j = 'focus down'
    # cmd-alt-ctrl-j = 'focus down'
    alt-k = 'focus up'
    # cmd-alt-ctrl-k = 'focus up'
    alt-l = 'focus right'
    # cmd-alt-ctrl-l = 'focus right'

    alt-shift-h = 'move left'
    # cmd-alt-ctrl-shift-h = 'move left'
    alt-shift-j = 'move down'
    # cmd-alt-ctrl-shift-j = 'move down'
    alt-shift-k = 'move up'
    # cmd-alt-ctrl-shift-k = 'move up'
    alt-shift-l = 'move right'
    # cmd-alt-ctrl-shift-l = 'move right'

    alt-1 = 'workspace 1' # Browser 1
    # cmd-alt-ctrl-1 = 'workspace 1'
    alt-2 = 'workspace 2' # Browser 1
    # cmd-alt-ctrl-2 = 'workspace 2'
    alt-3 = 'workspace 3' # App for work
    # cmd-alt-ctrl-3 = 'workspace 3'
    alt-4 = 'workspace 4' # Notes
    # cmd-alt-ctrl-4 = 'workspace 4'
    alt-5 = 'workspace 5' # Telegram
    # cmd-alt-ctrl-5 = 'workspace 5'
    alt-6 = 'workspace 6' # Spotify
    # cmd-alt-ctrl-6 = 'workspace 6'
    alt-7 = 'workspace 7' # Reminders
    # cmd-alt-ctrl-7 = 'workspace 7'
    alt-8 = 'workspace 8' # Calendar
    # cmd-alt-ctrl-8 = 'workspace 8'
    alt-9 = 'workspace 9' # Mail
    # cmd-alt-ctrl-9 = 'workspace 9'
    alt-0 = 'workspace 10' # Other
    # cmd-alt-ctrl-0 = 'workspace 10'
    alt-t = 'workspace T' # Terminal
    # cmd-alt-ctrl-t = 'workspace T'

    alt-shift-1 = 'move-node-to-workspace 1'
    # cmd-alt-ctrl-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    # cmd-alt-ctrl-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    # cmd-alt-ctrl-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    # cmd-alt-ctrl-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    # cmd-alt-ctrl-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    # cmd-alt-ctrl-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    # cmd-alt-ctrl-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    # cmd-alt-ctrl-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    # cmd-alt-ctrl-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'
    # cmd-alt-ctrl-shift-0 = 'move-node-to-workspace 10'
    alt-shift-t = 'move-node-to-workspace T'
    # cmd-alt-ctrl-shift-t = 'move-node-to-workspace T'

    alt-enter = ['exec-and-forget open -a /Applications/iTerm.app', 'workspace T']
    # cmd-alt-ctrl-enter = 'exec-and-forget open -a /Applications/iTerm.app'
    cmd-alt-ctrl-f = 'exec-and-forget open -a "Finder"'
    cmd-alt-ctrl-b = 'exec-and-forget open -a /Applications/Safari.app'
    cmd-alt-ctrl-shift-b = 'exec-and-forget open -a /Applications/Google\ Chrome.app'
    cmd-alt-ctrl-n = 'exec-and-forget open -a /Applications/Obsidian.app'
    cmd-alt-ctrl-g = 'exec-and-forget open -a /Applications/Telegram.app'
    cmd-alt-ctrl-c = 'exec-and-forget open -a /System/Applications/Calendar.app'
    cmd-alt-ctrl-e = 'exec-and-forget open -a /System/Applications/Mail.app'
    cmd-alt-ctrl-m = 'exec-and-forget open -a /Applications/Spotify.app'
    cmd-alt-ctrl-a = 'exec-and-forget open -a /Applications/ChatGPT.app'
    cmd-alt-ctrl-v = 'exec-and-forget open -a /Applications/Hiddify.app'

[workspace-to-monitor-force-assignment]
    1 = 'main'
    2 = 'main'
    3 = 'main'
    4 = 'main'
    5 = 'main'
    6 = 'main'
    7 = 'main'
    8 = 'main'
    9 = 'main'
    10 = ['secondary', 'main']
    T = 'main'

[[on-window-detected]]
    if.app-id = 'com.apple.Safari'
    run = "move-node-to-workspace 1"

[[on-window-detected]]
    if.app-id = 'com.google.Chrome'
    run = "move-node-to-workspace 2"

[[on-window-detected]]
    if.app-id = 'org.jkiss.dbeaver.core.product'
    run = 'move-node-to-workspace 3'
[[on-window-detected]]
    if.app-id = 'com.figma.Desktop'
    run = 'move-node-to-workspace 3'
[[on-window-detected]]
    if.app-id = 'org.gimp.gimp-3.0'
    run = 'move-node-to-workspace 3'

[[on-window-detected]]
    if.app-id = 'md.obsidian'
    run = 'move-node-to-workspace 4'

[[on-window-detected]]
    if.app-id = 'com.tdesktop.Telegram'
    run = 'move-node-to-workspace 5'

[[on-window-detected]]
    if.app-id = 'com.spotify.client'
    run = 'move-node-to-workspace 6'

[[on-window-detected]]
    if.app-id = 'com.apple.reminders'
    run = 'move-node-to-workspace 7'

[[on-window-detected]]
    if.app-id = 'com.apple.iCal'
    run = 'move-node-to-workspace 8'

[[on-window-detected]]
    if.app-id = 'com.apple.mail'
    run = 'move-node-to-workspace 9'

[[on-window-detected]]
    if.app-id = 'com.valvesoftware.steam.helper'
    run = ['layout tiling', 'move-node-to-workspace 10']

[[on-window-detected]]
    if.app-id = "com.googlecode.iterm2"
    run = "move-node-to-workspace T"
