start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]
    cmd-h = []     # Disable "hide application"
    cmd-alt-h = [] # Disable "hide others"

    cmd-alt-ctrl-shift-c = 'reload-config'
    cmd-alt-ctrl-shift-f = 'fullscreen'
    cmd-alt-ctrl-shift-t = 'layout floating tiling'

    cmd-alt-ctrl-tab = 'workspace-back-and-forth'
    cmd-alt-ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    cmd-alt-ctrl-shift-minus = 'resize smart -50'
    cmd-alt-ctrl-shift-equal = 'resize smart +50'

    cmd-alt-ctrl-h = 'focus left'
    cmd-alt-ctrl-j = 'focus down'
    cmd-alt-ctrl-k = 'focus up'
    cmd-alt-ctrl-l = 'focus right'

    cmd-alt-ctrl-shift-h = 'move left'
    cmd-alt-ctrl-shift-j = 'move down'
    cmd-alt-ctrl-shift-k = 'move up'
    cmd-alt-ctrl-shift-l = 'move right'

    cmd-alt-ctrl-1 = 'workspace 1'
    cmd-alt-ctrl-2 = 'workspace 2'
    cmd-alt-ctrl-3 = 'workspace 3'
    cmd-alt-ctrl-4 = 'workspace 4'
    cmd-alt-ctrl-shift-1 = 'move-node-to-workspace 1'
    cmd-alt-ctrl-shift-2 = 'move-node-to-workspace 2'
    cmd-alt-ctrl-shift-3 = 'move-node-to-workspace 3'
    cmd-alt-ctrl-shift-4 = 'move-node-to-workspace 4'

    cmd-alt-ctrl-a = 'exec-and-forget open -a /Users/$(whoami)/Applications/ChatGPT.app'
    cmd-alt-ctrl-b = ['workspace [B]rowser', 'exec-and-forget open -a /Applications/Safari.app']
    cmd-alt-ctrl-c = ['workspace [C]alendar', 'exec-and-forget open -a /System/Applications/Calendar.app']
    cmd-alt-ctrl-d = ['workspace [D]atabase', 'exec-and-forget open -a /Applications/DBeaver.app']
    cmd-alt-ctrl-e = ['workspace [E]mail', 'exec-and-forget open -a /System/Applications/Mail.app']
    cmd-alt-ctrl-f = 'exec-and-forget open -a Finder'
    cmd-alt-ctrl-g = ['workspace [G]UI', 'exec-and-forget open -a /Applications/Figma.app']
    cmd-alt-ctrl-m = ['workspace [M]usic', 'exec-and-forget open -a /Applications/Spotify.app']
    cmd-alt-ctrl-n = ['workspace [N]otes', 'exec-and-forget open -a /Applications/Obsidian.app']
    cmd-alt-ctrl-p = ['workspace [P]aint', 'exec-and-forget open -a /Users/$(whoami)/Applications/Excalidraw.app']
    cmd-alt-ctrl-r = ['workspace [R]eddit', 'exec-and-forget open -a /Users/$(whoami)/Applications/Reddit.app']
    cmd-alt-ctrl-s = ['workspace [S]ocial', 'exec-and-forget open -a /Applications/Telegram.app']
    cmd-alt-ctrl-t = ['workspace [T]est', 'exec-and-forget open -a /Applications/Postman.app']
    cmd-alt-ctrl-w = ['workspace [W]ork', 'exec-and-forget open -a /Applications/Firefox.app']
    cmd-alt-ctrl-x = ['workspace [X]', 'exec-and-forget open -a /Users/$(whoami)/Applications/X.app']
    cmd-alt-ctrl-z = ['workspace [Z]ed', 'exec-and-forget open -a /Applications/Zed.app']
    cmd-alt-ctrl-enter = ['workspace [Return]', 'exec-and-forget open -a /Applications/iTerm.app']

[workspace-to-monitor-force-assignment]
    1 = 'main'
    2 = 'main'
    3 = 'main'
    4 = ['secondary', 'main']

[[on-window-detected]]
    if.app-id = 'com.apple.Safari'
    run = "move-node-to-workspace [B]rowser"
[[on-window-detected]]
    if.app-id = 'com.apple.iCal'
    run = 'move-node-to-workspace [C]alendar'
[[on-window-detected]]
    if.app-id = 'org.jkiss.dbeaver.core.product'
    run = 'move-node-to-workspace [D]atabase'
[[on-window-detected]]
    if.app-id = 'com.apple.mail'
    run = 'move-node-to-workspace [E]mail'
[[on-window-detected]]
    if.app-id = 'com.figma.Desktop'
    run = 'move-node-to-workspace [G]UI'
[[on-window-detected]]
    if.app-id = 'com.spotify.client'
    run = 'move-node-to-workspace [M]usic'
[[on-window-detected]]
    if.app-id = 'md.obsidian'
    run = 'move-node-to-workspace [N]otes'
[[on-window-detected]]
    if.app-id = 'com.tdesktop.Telegram'
    run = 'move-node-to-workspace [S]ocial'
[[on-window-detected]]
    if.app-id = 'com.postmanlabs.mac'
    run = 'move-node-to-workspace [T]est'
[[on-window-detected]]
    if.app-id = 'org.mozilla.firefox'
    run = "move-node-to-workspace [W]ork"
[[on-window-detected]]
    if.app-id = "dev.zed.Zed"
    run = "move-node-to-workspace [Z]ed"
[[on-window-detected]]
    if.app-id = "com.googlecode.iterm2"
    run = "move-node-to-workspace [Return]"
